/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test.dianying;




/**
 *
 * @author HNDX
 */
public class Dianyinggenggai extends javax.swing.JFrame {

    /**
     * Creates new form Dianyingzengtian
     */
    public Dianyinggenggai() {
        initComponents();
        setLocationRelativeTo(null);
        String sql = "select*from dianyingxinxi";
        //dianyingxinxi看作为一个TableModel
        DianyingINFO d = new DianyingINFO(sql);
        //教你如何添加数据的方法
        jTable1.setModel(d);
        System.out.println(" 已经给表添加好了数据！");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =  new Cuntu("/test/1F44E77EC5EEB5F97D92489E529A79E7DA558EE0_size91_w1080_h602.jpg")
        ;
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DYName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DYpiaojia = new javax.swing.JTextField();
        ChangcID = new javax.swing.JTextField();
        ChangTID = new javax.swing.JTextField();
        DYzhuyan = new javax.swing.JTextField();
        DYID = new javax.swing.JTextField();
        shijian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DYxiangqing = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 46, -1, -1));

        jLabel1.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("主演");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        DYName.setText("          ");
        DYName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DYNameActionPerformed(evt);
            }
        });
        jPanel1.add(DYName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 90, -1));

        jLabel5.setFont(new java.awt.Font("楷体", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   电 影 更 改");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, -1));

        jLabel6.setText("----------------------------------------------------");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 7));

        jButton1.setText("安全退出");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jButton2.setText("返回上一级");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jButton3.setText("确认更改");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, -1));

        jLabel8.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("电影名称");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("时长");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("场次ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("详情");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("场厅ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("电影ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("楷体", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("票价");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        DYpiaojia.setText("      ");
        jPanel1.add(DYpiaojia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, -1));

        ChangcID.setText("      ");
        ChangcID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangcIDActionPerformed(evt);
            }
        });
        jPanel1.add(ChangcID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));

        ChangTID.setText("      ");
        jPanel1.add(ChangTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, -1));

        DYzhuyan.setText("      ");
        jPanel1.add(DYzhuyan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 90, -1));

        DYID.setText("         ");
        jPanel1.add(DYID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, -1));

        shijian.setText("      ");
        jPanel1.add(shijian, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, -1));

        DYxiangqing.setColumns(20);
        DYxiangqing.setRows(5);
        jScrollPane2.setViewportView(DYxiangqing);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 130, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "电影ID", "电影名字", "主演", "时长     ", "场次ID", "场厅ID", "票价", "详情"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 600, 110));

        getContentPane().add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 //获取当前位置
        int index = jTable1.getSelectedRow();
        //获取某一行的第0列的值,注意获取的行数需要减少一个
        String id = jTable1.getValueAt(index - 1, 0).toString();     
        String dyID = DYID.getText().trim();
        String dyname = DYName.getText().trim();
        String zhyan = DYzhuyan.getText().trim();
        String shchang = shijian.getText().trim();
        String changcID = ChangcID.getText().trim();
        String changtID = ChangTID.getText().trim();
        String piaoji = DYpiaojia.getText().trim();
        String xqing = DYxiangqing.getText().trim();
        
         DYID.setText("");
        DYName.setText("");
        DYzhuyan.setText("");
        shijian.setText("");
        ChangcID.setText("");
         ChangTID.setText("");
          DYpiaojia.setText("");
           DYxiangqing.setText("");
           
            String sql = "UPDATE  dianyingxinxi SET dianyingID ='" + dyID + "',"
                    + "dianyingname ='" + dyname + "'," + "zhuyan='" + zhyan + "',shichang='" 
                    + shchang + "',ChangciID='" + changcID + "',ChangTingID='" 
                    + changtID + "',piaojia='"+ piaoji +"',dianyingxiangqing='"
                    + xqing +"' WHERE dianyingID='" + dyID + "'";
            System.out.println(sql);

        System.out.println(id);
        System.out.println(dyID);
        DianyingINFO df = new DianyingINFO();
        df.Update(sql);

      
         
         //重新读取数据
        String sql2= "select * from dianyingxinxi";
        DianyingINFO d = new DianyingINFO(sql2);
        jTable1.setModel(d);

       
      
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dianyingcaozuo obj = new Dianyingcaozuo();
        dispose();
        obj.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DYNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DYNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DYNameActionPerformed

    private void ChangcIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangcIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangcIDActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         //获取某一行的具体值，并把它显示在文本框中
        String dianyingID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String dianyingname =jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String zhuyan =jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String shichang = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String changciID = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String changtingID = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String piaojia = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
        String xiangqing =jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
       
        //把点击的内容显示在文本框中
          DYID.setText(dianyingID);
        DYName.setText(dianyingname);
        DYzhuyan.setText(zhuyan);
        shijian.setText(shichang);
        ChangcID.setText(changciID);
         ChangTID.setText(changtingID);
          DYpiaojia.setText(piaojia);
           DYxiangqing.setText(xiangqing);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dianyinggenggai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dianyinggenggai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dianyinggenggai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dianyinggenggai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Dianyinggenggai().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChangTID;
    private javax.swing.JTextField ChangcID;
    private javax.swing.JTextField DYID;
    private javax.swing.JTextField DYName;
    private javax.swing.JTextField DYpiaojia;
    private javax.swing.JTextArea DYxiangqing;
    private javax.swing.JTextField DYzhuyan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField shijian;
    // End of variables declaration//GEN-END:variables
}
